name: pihole-panel # you probably want to 'snapcraft register <name>'
version: '0.6' # just for humans, typically '1.2+git' or '1.3.2'
summary: Pi-hole statistics and control panel using Python and GTK3  # 79 char long summary
description: |
 PiHole-Panel is a statistics and control panel for the Pi-hole adblocker optimized for the Gnome 3 desktop.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pihole-panel:
    command: app.py


parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
